name: analysis
permissions: read-all
on: [ push, pull_request ]

env:
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 18 ]
    env:
      JAVA_VERSION: ${{ matrix.java }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
        with:
          egress-policy: audit
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - uses: gradle/gradle-build-action@v2
      - name: Run analyzers
        run: ./.github/scripts/analyze.sh
      - name: Stop Gradle daemon
        if: always()
        run: ./gradlew --stop
