name: Validate Gradle Wrapper
on: [push, pull_request]
permissions: read-all

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
        with:
          egress-policy: audit
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1.0.4
