name: Qodana
on: [ push, pull_request ]

env:
  ORG_GRADLE_PROJECT_checksumFailOn: never
  ORG_GRADLE_PROJECT_checksumIgnore: false
  ORG_GRADLE_PROJECT_checksumPrint: true
  JAVA_VERSION: 11

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x test
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@main
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
      - name: View Instructions
        run: |
          echo "Download and extract the report artifact"
          echo "Start an http server"
          echo "... python2 -m SimpleHTTPServer"
          echo "... python3 -m http.server"
          echo "The report is available at http://localhost:8000"
          echo "For more details see https://www.jetbrains.com/help/qodana"
