name: Semgrep
permissions: read-all
on:
  pull_request: {}
  push:
    branches: [master, v2.dev, v3.dev]

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: semgrep scan --sarif --output=semgrep.sarif
        env:
          SEMGREP_RULES: >-
            p/java
            p/github-actions
            p/semgrep-rule-lints
            p/semgrep-misconfigurations
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep.sarif
        if: always()
